Fix search conditions in ElasticSearch 7+
When searching for a given field value, an error occurs
with ElasticSearch 7 and later:
> parsing_exception: unknown query [filtered]

The "filtered" query used up to now was deprecated in version 6.8
and is not available in ElasticSearch 7 or later [1].

This patch uses the new correct query form when the detected
server version is at least 7.

Resolves: https://github.com/adminerevo/adminerevo/issues/160

[1] https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-filtered-query.html